builds:
  - binary: target
    id: target
    ldflags:
      - "-X github.com/devops-rob/target-cli/cmd.version={{.Version}}"
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    flags:
      - -mod=vendor

release:
  prerelease: auto

universal_binaries:
  - replace: true

brews:
  -
    name: target
    homepage: "https://github.com/devops-rob/target-cli"
    tap:
      owner: devops-rob
      name: homebrew-devops-rob
    commit_author:
      name: devops-rob
      email: robert.barnes@devopsrob.com
    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"
    license: "MIT"
checksum:
  name_template: 'checksums.txt'