builds:
  - binary: target
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    flags:
      - -mod=vendor

release:
  prerelease: auto

universal_binaries:
  - replace: true

brews:
  -
    name: target
    homepage: "https://github.com/devops-rob/target-cli"
    tap:
      owner: devops-rob
      name: homebrew-devops-rob
    commit_author:
      name: devops-rob
      email: robert.barnes@devopsrob.com
    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"
    license: "MIT"
    repository:
          # Repository owner.
          #
          # Templates: allowed
          owner: devops-rob

          # Repository name.
          #
          # Templates: allowed
          name: homebrew-devops-rob

          # Optionally a branch can be provided.
          #
          # Default: default repository branch
          # Templates: allowed
          branch: main


checksum:
  name_template: 'checksums.txt'